<?php
define('CLI_SCRIPT', true);
require('/bitnami/moodle/config.php');
require_once($CFG->libdir . '/filelib.php');
require_once($CFG->dirroot . '/course/lib.php');
require_once($CFG->dirroot . '/mod/scorm/lib.php');
require_once($CFG->dirroot . '/mod/scorm/locallib.php');

$options  = getopt('', ['courseid:', 'zippath:', 'name:']);
$courseid = (int)($options['courseid'] ?? 0);
$zippath  = $options['zippath'] ?? '';
$name     = $options['name'] ?? 'GovLearn Course';

if (!$courseid || !file_exists($zippath)) {
    echo "ERROR: --courseid and --zippath are required\n";
    exit(1);
}

$course = $DB->get_record('course', ['id' => $courseid], '*', MUST_EXIST);

// Get the real section record for section number 1
$section = $DB->get_record('course_sections', ['course' => $courseid, 'section' => 1]);
if (!$section) {
    $section = new stdClass();
    $section->course   = $courseid;
    $section->section  = 1;
    $section->sequence = '';
    $section->visible  = 1;
    $section->id = $DB->insert_record('course_sections', $section);
}

$fs       = get_file_storage();
$filename = basename($zippath);

// Insert SCORM record first (we need its ID for the CM)
$scorm = new stdClass();
$scorm->course          = $courseid;
$scorm->name            = $name;
$scorm->intro           = '<p>Interactive course generated by GovLearn.</p>';
$scorm->introformat     = FORMAT_HTML;
$scorm->scormtype       = SCORM_TYPE_LOCAL;
$scorm->reference       = $filename;
$scorm->version         = 'SCORM_12';
$scorm->maxgrade        = 100;
$scorm->grademethod     = GRADEHIGHEST;
$scorm->maxattempt      = 0;
$scorm->whatgrade       = GRADEHIGHEST;
$scorm->forcecompleted  = 0;
$scorm->forcenewattempt = 0;
$scorm->lastattemptlock = 0;
$scorm->displayattemptstatus = 1;
$scorm->displaycoursestructure = 0;
$scorm->updatefreq      = 0;
$scorm->sha1hash        = sha1_file($zippath);
$scorm->md5hash         = md5_file($zippath);
$scorm->revision        = 1;
$scorm->launch          = 0;
$scorm->skipview        = 1;
$scorm->hidebrowse      = 0;
$scorm->hidetoc         = 1;
$scorm->nav             = 0;
$scorm->auto            = 0;
$scorm->popup           = 0;
$scorm->options         = '';
$scorm->width           = 100;
$scorm->height          = 500;
$scorm->timeopen        = 0;
$scorm->timeclose       = 0;
$scorm->timemodified    = time();
$scorm->completionstatusrequired = 4;
$scorm->completionscorerequired  = 0;
$scorm->completionstatusallscos  = 0;
$scorm->visible         = 1;
$scorm->id = $DB->insert_record('scorm', $scorm);

// Insert course_modules record
$module = $DB->get_record('modules', ['name' => 'scorm'], '*', MUST_EXIST);
$cm = new stdClass();
$cm->course   = $courseid;
$cm->module   = $module->id;
$cm->instance = $scorm->id;
$cm->section  = $section->id;
$cm->visible  = 1;
$cm->added    = time();
$cm->id = $DB->insert_record('course_modules', $cm);

$scorm->coursemodule = $cm->id;

// Add cm to section sequence
$seq = $section->sequence ? $section->sequence . ',' . $cm->id : (string)$cm->id;
$DB->set_field('course_sections', 'sequence', $seq, ['id' => $section->id]);

// Now create the MODULE context (requires CM to exist first)
$modcontext = context_module::instance($cm->id);

// Store the zip under the correct module context
$fs->delete_area_files($modcontext->id, 'mod_scorm', 'package', 0);
$filerecord = [
    'contextid' => $modcontext->id,
    'component' => 'mod_scorm',
    'filearea'  => 'package',
    'itemid'    => 0,
    'filepath'  => '/',
    'filename'  => $filename,
];
$fs->create_file_from_pathname($filerecord, $zippath);

// Parse SCORM manifest (now has correct context)
scorm_parse($scorm, true);

// Rebuild course cache
rebuild_course_cache($courseid, true);

echo "OK:{$cm->id}\n";
