#!/usr/bin/env python3
"""
GovLearn Moodle course creator.
Reads knowledge_base.json and creates a full Moodle course via REST API.

Usage:
  python create_moodle_course.py
  python create_moodle_course.py --kb knowledge_base.json --module-id cyber-101
"""

import argparse
import json
import os
import re
import sys
import requests
from urllib.parse import urlparse

# --- CONFIG ---

MOODLE_URL = os.environ.get("MOODLE_URL", "http://192.168.122.153:8080")
MOODLE_TOKEN = os.environ.get("MOODLE_TOKEN", "d687610cf5075667f4b0c79dea1957c0")
DATABASE_URL = os.environ.get("DATABASE_URL", "")
CHATBOT_URL = os.environ.get("CHATBOT_URL", "http://localhost:8000")
CATEGORY_ID = 1  # Default Moodle category

API = f"{MOODLE_URL}/webservice/rest/server.php"


def call(wsfunction: str, **params) -> dict | list:
    """Make a Moodle REST API call."""
    data = {
        "wstoken": MOODLE_TOKEN,
        "wsfunction": wsfunction,
        "moodlewsrestformat": "json",
        **params,
    }
    resp = requests.post(API, data=data, timeout=30)
    resp.raise_for_status()
    result = resp.json()
    if isinstance(result, dict) and "exception" in result:
        raise RuntimeError(f"Moodle API error [{wsfunction}]: {result.get('message')} ({result.get('errorcode')})")
    return result


# --- COURSE CREATION ---

def create_course(module_id: str, title: str) -> int:
    """Create the top-level Moodle course. Returns course id."""
    # Delete existing course with same shortname if present
    existing = call("core_course_get_courses_by_field", field="shortname", value=module_id)
    if existing.get("courses"):
        print(f"  ⚠ Course '{module_id}' already exists, deleting...")
        existing_id = existing["courses"][0]["id"]
        call("core_course_delete_courses", **{"courseids[0]": existing_id})
        print(f"  ✓ Deleted course id={existing_id}")

    result = call(
        "core_course_create_courses",
        **{
            "courses[0][fullname]": title,
            "courses[0][shortname]": module_id,
            "courses[0][categoryid]": CATEGORY_ID,
            "courses[0][summary]": f"Auto-generated by GovLearn from policy document. Module: {module_id}",
            "courses[0][summaryformat]": 1,
            "courses[0][format]": "topics",
            "courses[0][numsections]": 10,
            "courses[0][visible]": 1,
        },
    )
    course_id = result[0]["id"]
    print(f"  ✓ Created course: '{title}' (id={course_id})")
    return course_id


# --- SECTION / PAGE CREATION ---

def get_sections(course_id: int) -> list:
    """Get all sections for a course."""
    return call("core_course_get_contents", courseid=course_id)


def add_page(course_id: int, section: int, title: str, content: str) -> dict:
    """Add a page resource to a course section."""
    html = markdown_to_html(content)
    return call(
        "local_govlearn_create_page",
        courseid=course_id,
        sectionnum=section,
        name=title,
        content=html,
        visible=1,
    )


def markdown_to_html(text: str) -> str:
    """Convert basic markdown to HTML for Moodle pages."""
    lines = text.split("\n")
    html_lines = []
    in_list = False

    for line in lines:
        # Headers
        if line.startswith("### "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h3>{line[4:].strip()}</h3>")
        elif line.startswith("## "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h2>{line[3:].strip()}</h2>")
        elif line.startswith("# "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h1>{line[2:].strip()}</h1>")
        # Bullet points
        elif line.startswith("- ") or line.startswith("* "):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            item = line[2:].strip()
            item = apply_inline(item)
            html_lines.append(f"<li>{item}</li>")
        # Horizontal rule
        elif line.strip() in ("---", "***", "___"):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append("<hr/>")
        # Checkbox list items
        elif line.strip().startswith("- [ ]") or line.strip().startswith("- [x]"):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            item = re.sub(r"- \[[ x]\] ", "", line).strip()
            item = apply_inline(item)
            html_lines.append(f"<li>☐ {item}</li>")
        # Blockquote
        elif line.startswith("> "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<blockquote>{apply_inline(line[2:])}</blockquote>")
        # Empty line
        elif line.strip() == "":
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append("<br/>")
        # Regular paragraph
        else:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<p>{apply_inline(line)}</p>")

    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)


def apply_inline(text: str) -> str:
    """Apply inline markdown: bold, italic, code."""
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    return text


# --- QUIZ CREATION ---

def parse_quiz_content(content: str) -> list:
    """Parse the quiz section text into structured questions."""
    questions = []
    # Split on Q: blocks
    blocks = re.split(r"\n(?=Q\d*:|Q: )", content.strip())

    for block in blocks:
        block = block.strip()
        if not block:
            continue

        q_match = re.search(r"Q\d*:\s*(.+?)(?=\nA\))", block, re.DOTALL)
        if not q_match:
            continue
        question_text = q_match.group(1).strip()

        options = {}
        for letter in ["A", "B", "C", "D"]:
            opt_match = re.search(rf"{letter}\)\s*(.+?)(?=\n[B-D]\)|\nCorrect:|\Z)", block, re.DOTALL)
            if opt_match:
                options[letter] = opt_match.group(1).strip()

        correct_match = re.search(r"Correct:\s*([A-D])", block)
        correct = correct_match.group(1) if correct_match else "A"

        exp_match = re.search(r"Explanation:\s*(.+)", block, re.DOTALL)
        explanation = exp_match.group(1).strip() if exp_match else ""

        if question_text and len(options) >= 2:
            questions.append({
                "question": question_text,
                "options": options,
                "correct": correct,
                "explanation": explanation,
            })

    return questions


def create_quiz(course_id: int, section: int, module_id: str, questions: list) -> None:
    """Create a quiz with questions in Moodle via the local_govlearn plugin."""
    if not questions:
        print("  ⚠ No quiz questions parsed, skipping quiz creation.")
        return

    api_questions = []
    for q in questions:
        api_questions.append({
            "questiontext": q["question"],
            "optiona": q["options"].get("A", ""),
            "optionb": q["options"].get("B", ""),
            "optionc": q["options"].get("C", ""),
            "optiond": q["options"].get("D", ""),
            "correct": q["correct"],
            "explanation": q["explanation"],
        })

    params = {
        "courseid": course_id,
        "sectionnum": section,
        "name": "Knowledge Check",
        "intro": "<p>Test your understanding of the module content.</p>",
    }
    for i, q in enumerate(api_questions):
        for key, val in q.items():
            params[f"questions[{i}][{key}]"] = val

    result = call("local_govlearn_create_quiz", **params)
    print(f"  ✓ Quiz created ({result.get('questioncount', len(questions))} questions)")


# --- SELF-ENROLMENT ---

def enable_self_enrolment(course_id: int) -> None:
    """Enable self-enrolment so users can join without admin intervention."""
    if not DATABASE_URL:
        print("  ⚠ DATABASE_URL not set, skipping self-enrolment setup")
        return
    try:
        import psycopg2
        conn = psycopg2.connect(DATABASE_URL)
        conn.autocommit = True
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO mdl_enrol (enrol, status, courseid, sortorder, name,
                                       enrolperiod, expirenotify, expirynotify,
                                       notifyall, password, cost, currency,
                                       roleid, customint1, customint2, customint3,
                                       customint4, customint5, customint6,
                                       customint7, customint8, timecreated, timemodified)
                SELECT 'self', 0, %s, 0, 'Self enrolment',
                       0, 0, 0, 0, '', 0, '',
                       5, 0, 1, 0, 1, 0, 1, -1, 0,
                       EXTRACT(EPOCH FROM NOW())::int,
                       EXTRACT(EPOCH FROM NOW())::int
                WHERE NOT EXISTS (
                    SELECT 1 FROM mdl_enrol WHERE enrol='self' AND courseid=%s
                )
                """,
                (course_id, course_id),
            )
        conn.close()
        print("  ✓ Self-enrolment enabled")
    except Exception as e:
        print(f"  ⚠ Self-enrolment setup failed: {e}")


# --- PGVECTOR INGESTION ---

def ingest_to_pgvector(kb_path: str) -> None:
    """POST knowledge_base.json chunks to the chatbot /ingest endpoint."""
    try:
        with open(kb_path) as f:
            chunks = json.load(f)
        if not chunks:
            print("  ⚠ knowledge_base.json is empty, skipping pgvector ingestion")
            return
        ok = 0
        for chunk in chunks:
            resp = requests.post(f"{CHATBOT_URL}/ingest", json=chunk, timeout=30)
            if resp.status_code == 200:
                ok += 1
            else:
                print(f"  ⚠ Ingest chunk failed: {resp.status_code} {resp.text[:120]}")
        print(f"  ✓ Ingested {ok}/{len(chunks)} chunks into pgvector")
    except Exception as e:
        print(f"  ⚠ pgvector ingestion failed: {e}")


# --- MAIN ---

def build_course(kb_path: str, module_id: str) -> None:
    print(f"\n🎓 GovLearn Moodle Course Builder")
    print(f"   KB: {kb_path}")
    print(f"   Module: {module_id}")
    print(f"   Moodle: {MOODLE_URL}\n")

    # Load knowledge base
    with open(kb_path) as f:
        chunks = json.load(f)

    if not chunks:
        print("✗ knowledge_base.json is empty.")
        sys.exit(1)

    # Derive title from first chunk's section or module_id
    first_section = chunks[0].get("section", "")
    title = f"GovLearn: {module_id.upper()} — {first_section}" if first_section else f"GovLearn Module: {module_id}"
    title = title[:255]  # Moodle fullname limit

    # 1. Create course
    print("Step 1: Creating course...")
    course_id = create_course(module_id, title)

    # 2. Add sections/pages
    print("\nStep 2: Adding content pages...")
    quiz_chunk = None
    content_chunks = []

    for chunk in chunks:
        section_id = chunk.get("metadata", {}).get("section_id", "")
        if "quiz" in section_id.lower():
            quiz_chunk = chunk
        else:
            content_chunks.append(chunk)

    for i, chunk in enumerate(content_chunks, 1):
        section_title = chunk["section"]
        content = chunk["content"]
        print(f"  Adding page {i}: {section_title[:60]}...")
        try:
            add_page(course_id, i, section_title, content)
            print(f"  ✓ Page added")
        except Exception as e:
            print(f"  ⚠ Failed: {e}")

    # 3. Add quiz
    print("\nStep 3: Adding quiz...")
    quiz_section = len(content_chunks) + 1
    if quiz_chunk:
        questions = parse_quiz_content(quiz_chunk["content"])
        print(f"  Parsed {len(questions)} questions from quiz content")
        create_quiz(course_id, quiz_section, module_id, questions)
    else:
        print("  ⚠ No quiz chunk found in knowledge_base.json")

    # 4. Enable self-enrolment
    print("\nStep 4: Enabling self-enrolment...")
    enable_self_enrolment(course_id)

    # 5. Ingest into pgvector for chatbot
    print("\nStep 5: Ingesting into pgvector...")
    ingest_to_pgvector(kb_path)

    print(f"\n✅ Course built successfully!")
    print(f"   URL: {MOODLE_URL}/course/view.php?id={course_id}")


def main():
    parser = argparse.ArgumentParser(description="GovLearn Moodle course creator")
    parser.add_argument("--kb", default="knowledge_base.json", help="Path to knowledge_base.json")
    parser.add_argument("--module-id", default="cyber-101", help="Module ID slug")
    args = parser.parse_args()

    kb_path = args.kb
    if not os.path.isabs(kb_path):
        kb_path = os.path.join(os.path.dirname(__file__), kb_path)

    if not os.path.exists(kb_path):
        print(f"✗ knowledge_base.json not found at: {kb_path}")
        sys.exit(1)

    build_course(kb_path, args.module_id)


if __name__ == "__main__":
    main()
